# Generated by Django 3.1.1 on 2020-09-17 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_auto_20200916_2201'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='empleado',
        ),
        migrations.AlterModelTable(
            name='type',
            table='type',
        ),
    ]
